module.exports = {
  preset: 'jest-expo',
  setupFilesAfterEnv: ['@testing-library/jest-native/extend-expect'],
  collectCoverage: true,
  collectCoverageFrom: [
    '!<rootDir>/coverage/',
    '!<rootDir>/functions/',
    '!<rootDir>/node_modules/',
    '!<rootDir>/wiki/',
    '!<rootDir>/babel.config.js',
    '!<rootDir>/metro.config.js',
    '!<rootDir>/**/*.d.ts',
    'src/**/*.{ts,tsx}',
    '!src/**/*.styles.ts',
    '!src/**/index.ts',
    '!src/@enumerations/**',
    '!src/@interfaces/**',
    '!src/@mocks/**',
    '!src/@types/**',
    '!src/assets/**',
    '!src/theme/**',
    '!src/setupTests.ts',
  ],
};
